application: cn-escualos
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: res/favicon.ico
  upload: res/favicon\.ico

- url: /template\.css
  static_files: templates/template.css
  upload: templates/template\.css

- url: /res
  static_dir: res

- url: /templates
  static_dir: templates
  application_readable: yes

- url: /
  script: handlers.main.app

- url: /ensure_login
  script: handlers.ensure_login.app

- url: /member/modify
  script: handlers.member.modify.app
  login: required

- url: /member/open_competitions
  script: handlers.member.open_competitions.app
  login: required

- url: /member/participation_record
  script: handlers.member.participation_record.app
  login: required

- url: /member/record/add
  script: handlers.member.record.add.app
  login: required

- url: /member/record/delete
  script: handlers.member.record.delete.app
  login: required

- url: /member/record/show_all
  script: handlers.member.record.show_all.app

- url: /members
  script: handlers.members.app

- url: /trials
  script: handlers.trials.app

- url: /news
  script: handlers.news.app

- url: /photos
  script: handlers.photos.app

- url: /docs
  script: handlers.docs.app

- url: /docserver
  script: handlers.docserver.app

- url: /photoserver
  script: handlers.photoserver.app

- url: /error
  script: handlers.error.app

- url: /results
  script: handlers.results.app

- url: /info
  script: handlers.info.app

- url: /competition/management
  script: handlers.competition.management.app
  login: admin

- url: /competition/add
  script: handlers.competition.add.app
  login: admin

- url: /competition/modify
  script: handlers.competition.modify.app
  login: admin

- url: /competition/delete
  script: handlers.competition.delete.app
  login: admin

- url: /competition/test/add
  script: handlers.competition.test.add.app
  login: admin

- url: /competition/test/delete
  script: handlers.competition.test.delete.app
  login: admin

- url: /participation_record/modify
  script: handlers.participation_record.modify.app
  login: admin

- url: /participation_record/generate_csv
  script: handlers.participation_record.generate_csv.app
  login: admin

- url: /participation_record/member_participation/modify
  script: handlers.participation_record.member_participation.modify.app
  login: required

- url: /participation_record/member_participation/delete
  script: handlers.participation_record.member_participation.delete.app
  login: required

- url: /participation_record/member_participation/retrieve_payment
  script: handlers.participation_record.member_participation.retrieve_payment.app
  login: required

- url: /participation_record/participant_per_test/modify
  script: handlers.participation_record.participant_per_test.modify.app
  login: required

- url: /participation_record/participant_per_test/delete
  script: handlers.participation_record.participant_per_test.delete.app
  login: required

- url: /kernel
  script: handlers.kernel.app
  login: admin

- url: /admin_old
  script: handlers.admin_old.app
  login: admin

- url: /admin/patreons
  script: handlers.admin.patreons.app
  login: admin

- url: /admin/patreon/delete
  script: handlers.admin.patreon.delete.app
  login: admin

- url: /admin/trials
  script: handlers.admin.trials.app
  login: admin

- url: /admin/trial/delete
  script: handlers.admin.trial.delete.app
  login: admin

- url: /admin/photos
  script: handlers.admin.photos.app
  login: admin

- url: /admin/photo/delete
  script: handlers.admin.photo.delete.app
  login: admin

- url: /admin/member/generate_csv
  script: handlers.admin.member.generate_csv.app
  login: admin

- url: /admin/member/import_records
  script: handlers.admin.member.import_records.app
  login: admin

- url: /admin/patreon/delete
  script: handlers.admin.patreon.delete.app
  login: admin

- url: /admin/member/delete
  script: handlers.admin.member.delete.app
  login: admin

- url: /admin/members
  script: handlers.admin.members.app
  login: admin

- url: .*
  script: handlers.error.app

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest

- name: PIL
  version: latest
