application: cn-escualos
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: res/favicon.ico
  upload: res/favicon\.ico

- url: /template\.css
  static_files: templates/template.css
  upload: templates/template\.css

- url: /res
  static_dir: res

- url: /templates
  static_dir: templates
  application_readable: yes

- url: /
  script: handlers.main.app

- url: /ensure_login
  script: handlers.ensure_login.app
  login: required

- url: /member/modify
  script: handlers.member.modify.app
  login: required

- url: /member/record/add
  script: handlers.member.record.add.app
  login: required

- url: /member/record/delete
  script: handlers.member.record.delete.app
  login: required

- url: /member/record/show_all
  script: handlers.member.record.show_all.app

- url: /members
  script: handlers.members.app

- url: /trials
  script: handlers.trials.app

- url: /news
  script: handlers.news.app

- url: /photos
  script: handlers.photos.app

- url: /docs
  script: handlers.docs.app

- url: /docserver
  script: handlers.docserver.app

- url: /error
  script: handlers.error.app

- url: /info
  script: handlers.info.app

- url: /competition/management
  script: handlers.competition.management.app
  login: admin

- url: /competition/add
  script: handlers.competition.add.app
  login: admin

- url: /competition/modify
  script: handlers.competition.modify.app
  login: admin

- url: /competition/delete
  script: handlers.competition.delete.app
  login: admin

- url: /competition/test/add
  script: handlers.competition.test.add.app
  login: admin

- url: /kernel
  script: handlers.kernel.app
  login: admin

- url: /admin_old
  script: handlers.admin_old.app
  login: admin

- url: /admin/patreons
  script: handlers.admin.patreons.app
  login: admin

- url: /admin/patreon/delete
  script: handlers.admin.patreon.delete.app
  login: admin

- url: /admin/members
  script: handlers.admin.members.app
  login: admin

- url: .*
  script: handlers.error.app

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest

- name: PIL
  version: latest
